### ISSUE TITLE
[GPU specific] Required `selected-configuration.yaml` for helm workflow is outdated

### ISSUE THREAD

**Issue by JustinPan-goog** [suexu1025/MoE_study#16]
The `selected-configuration.yaml` and potentially `nemo-example.yaml` need an update to enable back helm execution. @hXl3s Would you mind to share the configuration/template you used for training? I would be happy to take it from there and create corresponding helm artificats, thanks!

**Comment by hXl3s** [comment]
The most up to date config is `config/experiment/gbs256_tpu.yaml`

**Comment by JustinPan-goog** [comment]
Thanks for pointing to it! I was thinking of the parallelization setup, which shouldn't impact convergence, but enable the experiment to run. My current setup is:
```yaml
tensor_parallelism: 8
context_parallelism: 1
pipeline_parallelism: 8
virtual_pipeline_parallelism: 1
```
